# Generated by Django 5.2.5 on 2025-08-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Subadministrador', 'Subadministrador'), ('Cajero', 'Cajero')], default='Cajero', max_length=20),
        ),
    ]
