# Generated by Django 5.2.5 on 2025-08-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_perfil_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='perfil',
            name='sucursales',
            field=models.ManyToManyField(blank=True, related_name='perfiles', to='inventario.sucursal'),
        ),
    ]
